version: '3.4'

services:
  tg-dice-bot:
    image: ghcr.io/deanxv/tg-dice-bot:latest
    container_name: tg-dice-bot
    restart: always
    volumes:
      - ./data/tgdicebot:/data
    environment:
      - SQL_DSN=tgdicebot:123456@tcp(db:3306)/dice_bot  # 请修改此行 SQL连接信息
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - TELEGRAM_API_TOKEN=123xxxxxxxxxyx57W2v1u123ew11  # 请修改此行 telegram-bot的token
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: 'root@123456' # 请修改此行 root用户名 密码
      MYSQL_USER: tgdicebot   # 创建专用用户
      MYSQL_PASSWORD: '123456'    # 设置专用用户密码
      MYSQL_DATABASE: dice_bot   # 自动创建数据库